import {rides,users,requests,notifications,id,getRide} from '../data/store.js';
export const list=(req,res)=>{let x=rides.filter(r=>r.status==='active');for(const k of ['from','to','date'])if(req.query[k])x=x.filter(r=>r[k].toLowerCase().includes(req.query[k].toLowerCase()));if(req.query.seats)x=x.filter(r=>r.availableSeats>=+req.query.seats);x=x.map(getRide);const s=req.query.sort;if(s==='cheapest')x.sort((a,b)=>a.price-b.price);if(s==='earliest')x.sort((a,b)=>a.time.localeCompare(b.time));if(s==='rating')x.sort((a,b)=>b.driver.rating-a.driver.rating);if(s==='seats')x.sort((a,b)=>b.availableSeats-a.availableSeats);res.json(x)};
export const one=(req,res)=>{const r=rides.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({message:'Ride not found.'});res.json(getRide(r))};
export const create=(req,res)=>{const {from,to,date,time,seats,price,vehicle,notes}=req.body;if(!from||!to||!date||!time||!seats||price===undefined)return res.status(400).json({message:'Please complete all ride details.'});const r={id:id('r'),driverId:req.user.id,from,to,date,time,seats:+seats,availableSeats:+seats,price:+price,vehicle,notes:notes||'',status:'active',duration:'45 min'};rides.unshift(r);res.status(201).json(getRide(r))};
export const requestRide=(req,res)=>{const r=rides.find(x=>x.id===req.params.id);const seats=+(req.body.requestedSeats||1);if(!r||r.status!=='active')return res.status(400).json({message:'This ride is no longer available.'});if(r.driverId===req.user.id)return res.status(400).json({message:'You cannot request your own ride.'});if(r.availableSeats<seats)return res.status(400).json({message:'Not enough seats available.'});if(requests.some(q=>q.rideId===r.id&&q.passengerId===req.user.id))return res.status(409).json({message:'You already requested this ride.'});const q={id:id('q'),rideId:r.id,passengerId:req.user.id,status:'pending',requestedSeats:seats,createdAt:new Date().toISOString()};requests.push(q);notifications.push({id:id('n'),userId:r.driverId,message:`New passenger request for ${r.from} → ${r.to}.`,type:'info',read:false,createdAt:new Date().toISOString()});res.status(201).json(q)};
export const mine=(req,res)=>res.json({offered:rides.filter(r=>r.driverId===req.user.id).map(getRide),requested:requests.filter(q=>q.passengerId===req.user.id).map(q=>({...q,ride:getRide(rides.find(r=>r.id===q.rideId))}))});
export const rideRequests=(req,res)=>{const r=rides.find(x=>x.id===req.params.id);if(!r||r.driverId!==req.user.id)return res.status(403).json({message:'Not allowed.'});res.json(requests.filter(q=>q.rideId===r.id).map(q=>{const u=users.find(x=>x.id===q.passengerId);const {password,...passenger}=u;return {...q,passenger}}))};
export const updateRequest=(req,res)=>{const q=requests.find(x=>x.id===req.params.id),r=q&&rides.find(x=>x.id===q.rideId);if(!q||!r||r.driverId!==req.user.id)return res.status(404).json({message:'Request not found.'});if(!['accepted','rejected'].includes(req.body.status))return res.status(400).json({message:'Invalid request status.'});q.status=req.body.status;if(q.status==='accepted')r.availableSeats-=q.requestedSeats;notifications.push({id:id('n'),userId:q.passengerId,message:`Your ride request was ${q.status}.`,type:q.status==='accepted'?'success':'warning',read:false,createdAt:new Date().toISOString()});res.json(q)};
export const stats=(req,res)=>res.json({users:users.length,rides:rides.length,active:rides.filter(r=>r.status==='active').length,completed:3,bookings:requests.length});
